#!/bin/bash

dir="$HOME/" #"/home/nikolay/"
dirname=".trash"
allway=$dir$dirname
filelog=".trash.log"
filerez=".res"
if [ ! -d $allway ]
then
    echo "Trash isn't found"
    exit 1
fi
name=$1

grep -Eh "/$name$" $allway/$filelog | awk -F: '{print}' > $allway/$filerez
input=$allway/$filerez
#while IFS= read -r line
for line in $(cat $allway/$filerez)
do
    ind=$(echo "$line" | awk -F: '{print $1}') 
    fullname=$(echo "$line" | awk -F: '{print $2}')
    way=$(echo "$line" | awk -F: '{print $2}' | grep -Eo "([/[:print:]]+)+/") 
    echo "$fullname - (y/n)?"
    read -n 1 answer
    #answer="y"
    if [[ $answer =~ [yY] ]]
    then	
        if [ -d $way ]
        then
	    if [ -f $way$name ]
	    then
		echo "File $name exists, new name $name.1"
	        name="$name.1"
	    fi
	    ln $allway/$ind $fullname 	#$way$name
	    rm -rf $allway/$ind
	    sed -i "/^$ind/d" $allway/$filelog
	else
            echo "Dir $way isn't found, file untrash in $dir."
	    ln $allway/$ind $dir$name
	    rm -rf $allway/$ind
	    sed -i "/^$ind/d" $allway/$filelog
        fi    
    fi	    
done
rm -rf $allway/$filerez
exit 0

