#!/bin/bash

dat=$(date +%Y-%m-%d)

backdir=$(ls $HOME | grep -E "(^Backup-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])+$" | sort | head -n 1 -r)
sour="source"
resdir="$HOME/restore"
if [  -d $HOME/$backdir ]
then
    if [ ! -d $resdir ]; then mkdir $resdir; fi
    if [ ! -d $resdir/$sout ]; then mkdir $resdir/$sout; fi
    allfiles=$(ls -a $HOME/$backdir/$sour/ | grep -Ev "(.[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])+$")
    echo $allfiles
    for file in $allfiles
    do
	    cp $HOME/$backdir/$sour/$file $resdir/ 
    done 
fi
